### ISSUE TITLE
Latest Version won't remove from plugin store after install

### ISSUE THREAD

**Issue by JamesStuder** [rajsekhar311/XrmToolBoxTools#1]
Looks like there is a version mismatch somewhere.  Says installed version is 1.2019.1.1 and latest is 1.2019.1.2.  Won't remove from plugin store after installing new or update.  I believe when this has happened in the past with other plugins it's a miss-match between the nuget package and the plugin.

**Comment by rajsekhar311** [comment]
Hi James,

Thanks for highlighting the issue, I will look into this and fix it.

Thanks,
Phani.

**Comment by rajsekhar311** [comment]
The issue is fixed with latest release.
