### ISSUE TITLE
Export to Excel

### ISSUE THREAD

**Issue by harryepstein** [rajsekhar311/XrmToolBoxTools#2]
Hi I have a request to make the hierarchy exportable or sharable in some way. I know this has been brought up before, but the tool is great but it's usefulness is limited by this. I can't even select multiple items from the list with left click + shift. How difficult is this to implement. At the very least, being able to select elements from the list for copy/paste to another program. Thanks!

**Comment by rajsekhar311** [comment]
Hi, I added export to excel feature to my tool. Please install the latest version (1.2021.1.7).
